# Base configuration for PFA PyTorch
dataset:
  name: "mnist"
  data_dir: "./data"
  iid: true

model:
  name: "cnn"
  num_classes: 10

training:
  algorithm: "fedavg"  # fedavg, pfa, pfa_plus
  num_clients: 10
  rounds: 100
  local_epochs: 5
  batch_size: 32
  lr: 0.1

privacy:
  enabled: false
  epsilon: 1.0
  delta: 1e-5
  noise_multiplier: 1.1

pfa:
  proj_dims: 1
  lanczos_iter: 64
  delay: false

logging:
  log_interval: 10
  save_model: false
  output_dir: "./outputs"
